### PR TITLE
bug Healing Duplicates Status Effect

### LINKED ISSUE #183: Healing Duplicates Status Effect
Initial wound:
image

Healing:
image

Results in fully healed with text status effects cleared but the token status effect is duplicated:
image

### PR DESCRIPTION
**Pull request by Moonpile**
Fixes #183

- Ensure that only one of "dead", "unconscious", or "shocked" will be displayed as a status.

### CODE REVIEW

File: src/items/hit-location-item/hitLocationSheet.ts [hunk 1]
```diff
@@ -297,6 +297,13 @@ export class HitLocationSheet extends RqgItemSheet<
 
   static async setTokenEffect(token: RqgToken, actorHealthBefore: ActorHealthState): Promise<void> {
```
Comment (wake42) [inline src/items/hit-location-item/hitLocationSheet.ts:298]: This parameter isn't used anymore so it could be removed (along with it's calculation where it's called)
```suggestion
  static async setTokenEffect(token: RqgToken): Promise<void> {
```
Maybe you could also remove my stray leftover comment row "TODO testing testing..." as well :-)

File: src/items/hit-location-item/hitLocationSheet.ts [hunk 2]
```diff
@@ -312,28 +319,27 @@ export class HitLocationSheet extends RqgItemSheet<
...
     const newEffect = health2Effect.get(token.actor.data.data.attributes.health);
 
-    if (newEffect?.label !== previousEffect?.label) {
-      const asOverlay = newEffect?.id === "dead";
-      const newEffectIsOn = !!token.actor.effects.find(
-        (e: ActiveEffect) => e.getFlag("core", "statusId") === newEffect?.id
-      );
-      const previousEffectIsOn = !!token.actor.effects.find(
-        (e: ActiveEffect) => e.getFlag("core", "statusId") === previousEffect?.id
+    for (const status of woundStatuses) {
```
Comment (wake42) [inline src/items/hit-location-item/hitLocationSheet.ts:324]: the constant woundStatuses is redundant since it's already defined in health2Effect
```suggestion
    for (const status of health2Effect.values()) {
```

**Review by wake42 — CHANGES_REQUESTED** [review]
Much better implementation than my previous one!

File: src/items/hit-location-item/hitLocationSheet.ts (hunk 1 above)
Comment (Moonpile) [reply src/items/hit-location-item/hitLocationSheet.ts]: Done

File: src/items/hit-location-item/hitLocationSheet.ts (hunk 2 above)
Comment (Moonpile) [reply src/items/hit-location-item/hitLocationSheet.ts]: Done.  I knew it was there but couldn't figure out how to get to it!

**Comment by Moonpile** [comment]
Finally got around to wrapping this one up

**Review by wake42 — APPROVED** [review]
